### PR TITLE
Week/02 06

### PR DESCRIPTION
**Pull request by akshita20**

### CODE REVIEW

**Comment by spallya** [comment]
Add exception handling using controller advice

**Comment by spallya** [comment]
Add proper http response status like 404, 400.  Suppose if a book is not found create custom book not found exception and handle it in your controller advice, send proper error using error dto and 404 http status code

**Comment by akshita20** [comment]
Added

**Comment by spallya** [comment]
looks good can merge now, Optional Task: Add swagger documentation

**Review by spallya — APPROVED** [review]

**Comment by akshita20** [comment]
> looks good can merge now, Optional Task: Add swagger documentation

sure, I'll add it and raise a separate PR.

**Pull request merged**
